require("plugins/nvim-tree")
require("plugins/lualine")
require("plugins/bufferline")
require("plugins/which-key")
require("plugins/nvim-treesitter")
require("plugins/telescope")
require("plugins/autopairs")
require("plugins/comment")
require("plugins/notify")
require("plugins/gitsigns")
require("plugins/sniprun")
require("plugins/rainbow")
require("plugins/colorizer")
require("plugins/alpha")
require("plugins/alternate")
require("plugins/todo-comments")
require("plugins/fidget")
require("plugins/bookmarks")
require("plugins/indent")
require("plugins/harpoon")
require("plugins/hop")

require("plugins/lspconfig")

-- No mover orden en que se cargan mason y cmp
require("plugins/mason")
require("plugins/cmp")
require("plugins/luasnip")
require("plugins/null-ls")
require("plugins/lsp-signature")
